version: '3'
services:
  ros2:
    build: .
    container_name: ros2_movement
    network_mode: "host"
    volumes:
      - ~/ros2_ws:/ros2_ws
    stdin_open: true  # docker run -i
    tty: true        # docker run -t
    ports:
      - "9090:9090"  # WebSocket port
    command: /bin/bash 