version: '3'
services:
  movement_controller:
    build: .
    container_name: ros2_movement_controller
    network_mode: "host"  # This allows the WebSocket server to be accessible from the host
    ports:
      - "9090:9090"  # Map container port 9090 to host port 9090
    volumes:
      - ./:/ros2_ws/src/movement_controller  # Mount the source code for development
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
              source /ros2_ws/install/setup.bash &&
              ros2 run movement_controller movement_controller" 